### ISSUE TITLE
Convex Hull Function in Cluster

### ISSUE THREAD

**Issue by akashShanmugraj** [TheR3dWizard/youSupply_Hackfest#14]

**Comment by akashShanmugraj** [comment]
For @OKeerthiKuttan

**Comment by akashShanmugraj** [comment]
@OKeerthiKuttan Should I add some small code snippets/comments in the lines where you need to do the modifications or are you all set?

**Comment by OKeerthiKuttan** [comment]
i am tryi g to add in the dynamic cluster into the cluster class itself
its kinda getting done ig
lets see
