### ISSUE TITLE
If a server stops, find a way for recovery of system data

### ISSUE THREAD

**Issue by akashShanmugraj** [TheR3dWizard/youSupply_Hackfest#25]
All the processed information, all the logic (nodes begin associated with clusters, cluster centroids) are not really stored anywhere on the database, instead they are stored in the system class's object instantiated in the flask server. If the server stops, all the logic along with it is lost.

Maybe think about Object Store / Object Database

**Comment by TheR3dWizard** [comment]
I think we can mark this as done now?

**Comment by akashShanmugraj** [comment]
Almost, only one more line of thought and one more commit. 
My line of thought goes like
- create a permanent volume for the Postgres docker container to run on everytime
- create functions (services) for the python code to reload all data from the database incase of improper server shutdown
