### ISSUE TITLE
look at the testalgo file and review it once

### ISSUE THREAD

**Issue by OKeerthiKuttan** [TheR3dWizard/youSupply_Hackfest#35]

**Comment by akashShanmugraj** [comment]
#34

**Comment by akashShanmugraj** [comment]
The implementation in `testalgo.py` looks awesome overall, but two places need some more clarity.

## `incremental` parameter in ConvexHull
Did you try the _incremental_ parameter of the convex hull object? If you are yet to, I think that might make the process even more efficient by not having to recompute many values over and over.

There you would be creating a ConvexHull object in the `__init__()` itself, like
```python
self.convexhullobject = ConvexHull(self.allnodes, incremental = True)
```

and then manipulate it however required in the `updatecentroid()` function

## Implementation `can_add_point()` function 
I saw that you created a function `can_add_point()` inside the cluster class that computes the distance between given coordinate and center of the cluster and returns whether it is within the thershold limit.

```python
class System:
    def addrequest(self, node: Node):
        for cluster in self.clusterlist:
            if cluster.can_add_point(np.array([node.x_pos, node.y_pos])):
                cluster.addnode(node)
                break
        else:
            new_cluster = Cluster(distancelimit=self.distancelimit)
            new_cluster.addnode(node)
            self.clusterlist.append(new_cluster)

```

But in the implementation, the code associates a single node with all the clusters it can reach to within the threshold limit. We dont want that, we only want the Node to be associated with the `nearest` cluster.

Also we haven't given much thought about `distancelimit` being a cluster attribute. All we know now for sure is system must have a `distancelimit` attribute. So can you change the `can_add_point()` function to return the distance alone, and we will do the comparision in the System class separately? 

## Variable Names
Can you give better variable names for `polygon_centroid()` function 🙂?

**Comment by akashShanmugraj** [comment]
Here is your checklist for today:

- [ ] Check if `incremental` param can be used, if yes update the `update_centroid()` function
- [ ] Review implementation of `can_add_point()` function in System class, modify it to return distance
- [ ] Give pretty variable names for `polygon_centriod()` function

**Comment by OKeerthiKuttan** [comment]
i cant figure out how to apply the incremental function yet also if the point has to be included into the neearest cluster it should first compare all the clusters ryt.
and ill revise the can_add_point and whats wronf with the centroid function name
