### ISSUE TITLE
New functions / classes for path calculation

### ISSUE THREAD

**Issue by akashShanmugraj** [TheR3dWizard/youSupply_Hackfest#36]
I cant describe what I need exactly but anyways I'll try 

- A method in the `System` class (or if separate class is the way to go then sure)
- should return list of objects of the type `Path`
- the path construction function should be able to calculate the paths for the following test cases
    - no elements in the cluster
    - only one node in the cluster
    - only one source in the cluster
    - only one sink in the cluster
    - non zero sources and non zero sinks that
        - are already perfectly satisfying (+6, +4, -10)
        - has an excess 
        - has a deficiency

You can make modifications in the `simulation.py` file and have `algorithmLogic.py` for reference

**Comment by TheR3dWizard** [comment]
in case of these test cases except the last one, the elements of the cluster must be added to the free pool, and for the last test case, the program works

**Comment by akashShanmugraj** [comment]
How to implement it, what functions do I call to get the paths?

**Comment by TheR3dWizard** [comment]
theres a getpath() function in Cluster class that will create the path and subpaths and put it as a class variable

**Comment by akashShanmugraj** [comment]
So after I insert a node inside one cluster, its fine to call the getpath() function for that class and update paths somewhere common like a database?

For example, will this work?

```python
def addrequest():
    body = request.get_json()

    newnode = Node(
        x_pos=body["xposition"],
        y_pos=body["yposition"],
        item=body["itemid"],
        quantity=body["quantity"],
    )
    updatedcluster = centralsystemobject.addrequest(newnode)
    updatedcluster.getpaths()
    return updatedcluster.subpaths
```

**Comment by akashShanmugraj** [comment]
@TheR3dWizard I saw this function in the Algorithm Class

```python
    def setSystem(self, system: System) -> None:
        if not self.system.isfeasiblesystem():
            raise ValueError("System does not contain sinks or sources and is not feasible")
        self.system.spectralclustering(num_points=100)
        #figure out what to do with the freepool system
        #possible solutions:
        #1) maybe create a new system 
        #2) change it from a system into just a list of nodes
        #3) change addNode to add a node to the freepool system and not the main system
        self.freepoolsystem = self.system.createfreepool()
        for cluster in self.system.clusterlist:
            cluster.getpath()
            self.paths.append(cluster.path)
```

according to this function, we are not doing anything with the free pool now?

and also we will replace `self.system.spectralclustering(num_points=100)` part right? because I cant get how we assumed that number of points is 100 right away

**Comment by akashShanmugraj** [comment]
In the remove path function from System class

```python
    def removePath(self, path: Path):
        for cluster in self.clusterlist:
            if path in cluster.subpaths:
                cluster.removepath(path)
        for node in path.path:
            self.removeNode(node)
```

shouldnt we also remove it from their respective clusters?

**Comment by akashShanmugraj** [comment]
@TheR3dWizard 

I tried this implementation

```python
alg = Algorithm()
# uncomment the following lines to test the code
nodelist = [
    Node(x_pos=1, y_pos=1, item="Flashlight", quantity=1), 
    Node(x_pos=2, y_pos=2, item="Flashlight", quantity=-1), 
    Node(x_pos=3, y_pos=3, item="Canned Food", quantity=-1),
    Node(x_pos=3, y_pos=0, item="Canned Food", quantity=1)
]

for node in nodelist:
    alg.addNode(node)
paths = alg.getPaths()
```

and I got this

```
Traceback (most recent call last):
  File "/Users/akashshanmugaraj/Documents/hackfestmain/AlgorithmLogic/algorithmlogic.py", line 613, in <module>
    alg.addNode(node)
  File "/Users/akashshanmugaraj/Documents/hackfestmain/AlgorithmLogic/algorithmlogic.py", line 589, in addNode
    self.setSystem(self.system)
  File "/Users/akashshanmugaraj/Documents/hackfestmain/AlgorithmLogic/algorithmlogic.py", line 573, in setSystem
    raise ValueError("System does not contain sinks or sources and is not feasible")
ValueError: System does not contain sinks or sources and is not feasible
```

**Comment by akashShanmugraj** [comment]
I thought you tested all the edge cases already

**Comment by TheR3dWizard** [comment]
This can be closed as well right?

**Comment by akashShanmugraj** [comment]
yep
